guild-analyzer/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :login, :only => [:create, :new, :destroy]
  resources :guilds do
    resources :contacts
  end



  root 'guilds#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

guild-analyzer/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

guild-analyzer/app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :guild

  validates :contact_alias, :rank, presence: true
end

guild-analyzer/app/models/guild.rb
class Guild < ApplicationRecord
  has_many :contacts, dependent: :destroy

  validates :server, presence: true
  validates :name, presence: true, uniqueness: true
end

guild-analyzer/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, :password_digest, :email, :gw2_character_id, presence: true
  validates :username, :email, :gw2_character_id, uniqueness: true
end

guild-analyzer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsConcern
  protect_from_forgery with: :exception
end

guild-analyzer/app/controllers/concerns/sessions_concern.rb
require 'active_support/concern'
module SessionsConcern
  extend ActiveSupport::Concern

  def session_logged_in?
    !session[:current_user_id].nil?
  end

  def session_user
    begin
      @current_user ||= User.find(session[:current_user_id])
    rescue ActiveRecord::RecordNotFound => e
      session.clear
      @current_user = nil
    end
  end

  def session_logout
    session.clear
  end

  def session_login user
    session[:current_user_id] = user.id
  end
end

guild-analyzer/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def create
    @guild = Guild.find(params[:guild_id])
    @contact = @guild.contacts.create(contact_params)
    redirect_to guild_path(@guild)
  end

   def destroy
    @guild = Guild.find(params[:guild_id])
    @contact = @guild.contacts.find(params[:id])
    @contact.destroy
    redirect_to guild_path(@guild)
  end


 def contact_params
    params.require(:contact).permit(:contact_alias, :rank)
  end
end

guild-analyzer/app/controllers/guilds_controller.rb
require 'rest-client'
require 'json'

class GuildsController < ApplicationController

  def index
    @guilds = Guild.all
    render :index
  end

  def new
    @guild  = Guild.new
    render :new
  end

  def create
    @guild = Guild.new(guild_params)
    url = "https://api.guildwars2.com/v1/guild_details.json?guild_name=#{@guild.name}"
    begin
      response = RestClient.get(url)
    rescue RestClient::BadRequest
      response = nil
    end

    if response != nil
      api_response = JSON.parse(response)
      @guild.guild_tag = api_response["tag"]
      if @guild.save
        redirect_to root_path
      else
        @guild.errors.full_messages
        render :new
      end
    else
      flash[:notice] = "Guild Name Can't Be Found"
      render :new
    end

  end

  def destroy
    @guild = Guild.find(params[:id])
    @guild.destroy
     p @guild.contacts

    redirect_to root_path
  end

  def edit
    @guild = Guild.find(params[:id])
    render :edit
  end

  def update
    @guild = Guild.find(params[:id])
    if @guild.update(guild_params)
      render :show
    else
      @guild.errors.full_messages
      render :edit
    end
  end

  def show
    @guild = Guild.find(params[:id])
    p @guild.contacts
    render :show
  end

  private
  def guild_params
    params.require(:guild).permit(:name, :server, :wvw_playstyle, :average_member_count, :guild_tag)
  end

end

guild-analyzer/app/controllers/login_controller.rb
class LoginController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by(email: params[:login][:email])
    if @user && @user.authenticate(params[:login][:password_digest])
      session_login @user
      redirect_to root_url
    else
      flash[:notice] = "Invalid Email/Password Combination"
      redirect_to new_login_path
    end
  end

  def destroy
    session_logout
    redirect_to root_url
  end

end

guild-analyzer/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user= User.new
    render :new
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def create
    @user = User.new(user_params)
    @user.password = user_params[:password_digest]
      if @user.save
        session_login @user
        redirect_to root_path
      else
        @user.errors.full_messages
        render :new
      end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :gw2_character_id, :password_digest, :encrypted_password)
  end

end

guild-analyzer/app/helpers/application_helper.rb
module ApplicationHelper
end

guild-analyzer/app/helpers/session_helper.rb
module SessionHelper
  def session_logged_in?
    !session[:current_user_id].nil?
  end

  def session_user
    begin
      @current_user ||= User.find(session[:current_user_id])
    rescue ActiveRecord::RecordNotFound => e
      session.clear
      @current_user = nil
    end
  end

  def session_logout
    session.clear
  end

  def session_login user
    session[:current_user_id] = user.id
  end
end

guild-analyzer/app/views/contacts/_new.html.erb
<%= form_for([@guild, @guild.contacts.build]) do |f| %>
  <%= f.text_field :contact_alias, placeholder: "Contact Alias" %>
  <%= f.text_field :rank, placeholder: "Rank in Guild", required: true %>
  <input type="submit" value="Add Contact"/>
<% end %>

guild-analyzer/app/views/guilds/edit.html.erb
<% if session_logged_in?%>
<section class="errors">
  <ul>
    <% @guild.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
</section>

<div class= "row">
  <div class="col-md-3 col-md-offset-5">
  <%= form_for @guild, url: guild_path(@guild), method: :patch do |f| %>
    <%= "Guild Name: #{@guild.name}" %> </br>
    <%= "Guild Tag: #{@guild.guild_tag}" %></br>
    <%= f.label "Server" %>
    <%= f.text_field :server %></br>
    <%= f.label "WvW Playstyle" %>
    <%= f.text_field :wvw_playstyle %></br>
    <%= f.label "Average Numbers" %>
    <%= f.text_field :average_member_count %></br>
    <%= f.submit %>
    <%= flash[:notice] %>
  <% end %>
  </div>
</div>
<% end %>

guild-analyzer/app/views/guilds/index.html.erb

<div class="center">
<h2>Guild List</h2>
	<% if session_logged_in?%>
    <%= link_to 'Add a New Guild', new_guild_path %></br></br>
    <p class="italic" style="font-size: 18px">To see details on a guild click on the name of the guild you want to see</p>
    <ul class="list-group">
      <% @guilds.each do |guild| %></br>
      <li class="list-item">
        <%= link_to "#{guild.name}[#{guild.guild_tag}]", guild_path(guild) , :class => 'guild-list' %>
      </li>
      <% end %>
    </ul>
  <% else %>
    <p class="center italic" style="font-size: 20px">This site is a way to store information on various guilds in the game guild wars 2. People input the information about the guild when they are logged in and can reference it later. In the future I plan to add more functionality to this and make it store more information as well as limiting who can make accounts.</p>
	<% end %>
</div>

guild-analyzer/app/views/guilds/new.html.erb
<section class="errors">
  <ul>
    <% @guild.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
</section>
<div class="row">
  <div class="col-md-5 col-md-offset-5">
    <h3>New Guild</h3>
      <%= flash[:notice] %>
      <%= form_for @guild do |f| %>
        <%= f.label "Name" %>
        <%= f.text_field :name%> </br>
        <%= f.label "Server" %>
        <%= f.text_field :server %></br>
        <%= f.label "WvW Playstyle" %>
        <%= f.text_field :wvw_playstyle %></br>
        <%= f.label "Average Numbers" %>
        <%= f.text_field :average_member_count %></br>
        <%= f.submit %>
      <% end %>
    </div>
</div>

guild-analyzer/app/views/guilds/show.html.erb
<div class="col-md-offset-5">
<h3>Guild Details</h2>
  <%= "Name: #{@guild.name}" %> </br>
  <%= "Guild Tag: #{@guild.guild_tag}" %></br>
  <%= "Server: #{@guild.server} "%></br>
  <%= "WvW Playstyle: #{@guild.wvw_playstyle}"%></br>
  <%= "Average WvW Numbers: #{@guild.average_member_count}" %></br>

  <%= link_to 'Edit Info', edit_guild_path %> |
  <%= link_to 'Delete', guild_path(@guild), method: :delete %>
</div>

<div class="center">
    <h4>Contacts</h4>
    <%= render "contacts/new" %>
    <div class="col-md-offset-5">
    <table class="table-bordered">
        <th>Name</th>
        <th>Rank</th>
        <th>Delete</th>
      <% @guild.contacts.each do |contact| %>
        <% if contact.id != nil %>
        <tr>
          <td><%= contact.contact_alias %></td>
          <td><%= contact.rank %></td>
          <td><%= link_to 'Delete', guild_contact_path(contact.guild_id, contact.id), method: :delete %> </td>
        </tr>
        <% end %>
      <% end %>
    </table>
    </div>
</div>

guild-analyzer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GuildAnalyzer</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-static-top navbar-default" role= "navigation">
    <div class="container">
      <ul class="nav navbar-left">
          <li><%= link_to "Home", root_path %></li>
        <% if session_logged_in? %>
          <li><%= link_to "#{session_user.username}", user_path(session_user) %></li>
          <li><%= link_to "Logout", login_path(session_user.id), :method => :delete %></li>
        <% else %>
          <li><%=link_to 'Register', new_user_path %></li>
          <li><%=link_to 'Login', new_login_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
    <h1 class= "center">Guild Wars 2 Guild Log</h1>
    <%= yield %>


  </body>
</html>

guild-analyzer/app/views/login/new.html.erb
<div class="row">
  <div class="col-md-3 col-md-offset-4">
  <h2 class="center">Login</h2>
    <%= flash[:notice] %>
    <%= form_for :login,  url: {action: "create"} do |f| %>
      <%= f.label "Email" %>
      <%= f.email_field :email, :class => 'form-control' %></br>
      <%= f.label "Password" %>
      <%= f.password_field :password_digest, :class => 'form-control' %></br>
      <%= f.submit :class => "btn btn-default", value: "Log In"%>
    <% end %>
  </div>
</div>

guild-analyzer/app/views/users/new.html.erb
<section class="errors">
  <ul>
    <% @user.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
</section>
 <div class="row">
    <div class="col-md-5 col-md-offset-4"">
      <%= form_for [@user] do |f| %>
        <%= f.label "Username" %>
        <%= f.text_field :username%> </br>
        <%= f.label "Guild Wars 2 character id" %>
        <%= f.text_field :gw2_character_id %></br>
        <%= f.label "Email" %>
        <%= f.email_field :email %></br>
        <%= f.label "Password" %>
        <%= f.password_field :password_digest %></br>
        <%= f.submit %>
        <%= flash[:notice] %>
      <% end %>
    </div>
  </div>

guild-analyzer/app/views/users/show.html.erb
<div class="center">
    <% if session_logged_in? %>
      <h2><%= "#{session_user.username}'s Profile" %></h2>
      <%= "Sign Up Date: #{(session_user.created_at).to_date.to_formatted_s(:long)}" %> </br>
      <%= "Guild Wars 2 Account ID: #{session_user.gw2_character_id}" %>
    <% end %>
</div>